name: Python CI

on: push

# I considered splitting this in to 3 separate jobs, but I couldn't really see the benefit of checking out the repo, python, and scan package 3 different times.
# Code is checked out once, python is installed, and pip is used to isntall flake8, safety, and bandit.
# Each step runs its corrisponding package.
jobs:
  scan:
    name: Scan Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 safety bandit

      # Run flake8 for linting.
      - name: Run flake8
        run: flake8 .

      # Run safety for dependency vulnerability, verify requirements.txt exists.
      - name: Run safety
        run: |
          if [ -f requirements.txt ]; then
            safety check -r requirements.txt
          else
            echo "requirements.txt not found, skipping safety check"
          fi

      # Run bandit to scan python files for security vunerabilities.
      - name: Run bandit
        run: |
          bandit -r .